# This file is processed by Renovate so that it creates a PR (notifying us) on new major Renovate versions
# Config for notification: https://github.com/insurgent-lab/.github/blob/main/.github/renovate.json
# Credit: https://www.augmentedmind.de/2023/07/30/renovate-bot-cheat-sheet/
FROM renovate/renovate:39
