# This file is processed by Renovate bot so that it creates a PR (notifying us) on new major Renovate versions
# Credit: https://www.augmentedmind.de/2023/07/30/renovate-bot-cheat-sheet/
FROM renovate/renovate:37
